const ROLES = {
  OWNER: 'owner',
  EDITOR: 'editor',
  VIEWER: 'viewer',
};

const ROLE_HIERARCHY = {
  [ROLES.OWNER]: 3,
  [ROLES.EDITOR]: 2,
  [ROLES.VIEWER]: 1,
};

const PERMISSIONS = {
  VIEW_PROJECT: [ROLES.OWNER, ROLES.EDITOR, ROLES.VIEWER],
  EDIT_DRAFT: [ROLES.OWNER, ROLES.EDITOR],
  PUSH_CHANGES: [ROLES.OWNER, ROLES.EDITOR],
  REVIEW_MERGE: [ROLES.OWNER, ROLES.EDITOR],
  ACCEPT_MERGE: [ROLES.OWNER],
  INVITE_MEMBERS: [ROLES.OWNER],
  MANAGE_MEMBERS: [ROLES.OWNER],
  DELETE_PROJECT: [ROLES.OWNER],
  RUN_EXECUTION: [ROLES.OWNER, ROLES.EDITOR],
  USE_TERMINAL: [ROLES.OWNER, ROLES.EDITOR],
  VIEW_CHAT: [ROLES.OWNER, ROLES.EDITOR, ROLES.VIEWER],
  SEND_CHAT: [ROLES.OWNER, ROLES.EDITOR, ROLES.VIEWER],
};

module.exports = {
  ROLES,
  ROLE_HIERARCHY,
  PERMISSIONS,
};